### ISSUE TITLE
Docker Image?

### ISSUE THREAD

**Issue by TJM** [devopshq/artifactory-du#10]
It would be nice if there was a docker image published under the `devopshq` namespace for this (and artifactory-cleanup) :)

**Comment by TJM** [comment]
```Dockerfile
FROM python:3-alpine

RUN python -mpip install artifactory-du && rm -rf ~/.cache
ENTRYPOINT [ "artifactory-du" ]
CMD [ "--help" ]
```

```bash
[tmcneely@local artifactory-du] $ docker images devopshq/artifactory-du:latest
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
devopshq/artifactory-du   latest              2d5060f6e416        12 seconds ago      52.8MB
[tmcneely@local artifactory-du] $ docker run devopshq/artifactory-du --version
artifactory-du 1.0.3
```

**Comment by allburov** [comment]
@Tim55667757 FYI - I've created devopshq organization in Docker Hub. Send me your or our shared docker hub account and I'll add you as an owner to the team.

**Comment by allburov** [comment]
I've pushed docker image. 
```
docker pull devopshq/artifactory-du
docker run devopshq/artifactory-du --version
```
@Tim55667757 @vasokot It's a manual action yet (releases are too rare here), I've added a new step in the "How to make a release" section in the README.md
@TJM thanks for the help!

**Comment by TJM** [comment]
Thanks guys!
