### ISSUE TITLE
Folders with sizes larger than 8 digits are not displayed properly

### ISSUE THREAD

**Issue by rpetti** [devopshq/artifactory-du#8]
Here's an example of what we are seeing:

```
106660929518jenkins
140280112597kazeon
191103053792ijms
221093243486bocs
275530520147ots
430796958060xplore
```

Offending code is here:
https://github.com/devopshq/artifactory-du/blob/14ab7f5207ef2c7bb5118ba4c7c402e4ba7e4b11/artifactory_du/du.py#L35

Ideally there should always be at least one space separating the size and the folder.

**Comment by allburov** [comment]
Fixed and merged in `master`. Thank you!
